version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  groups:
    bundler:
      patterns:
        - "*"
  open-pull-requests-limit: 15
  allow:
    - dependency-type: "all"
