inherit_from: .rubocop_todo.yml

require: rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*.rb'
