inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*.rb'

# Exclusions to make Rubocop play nicely with RSwag:
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/requests/**/*.rb'
RSpec/ExpectInHook:
  Exclude:
    - 'spec/requests/**/*.rb'
RSpec/VariableName:
  Exclude:
    - 'spec/requests/**/*.rb'
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/**/*.rb'
