version: '3'
services:
  app:
    build:
      context: .
      args:
        BUNDLE_DEPLOYMENT: 'false'
        BUNDLE_WITHOUT: ' ' # Intentional blank value
    volumes:
      - .:/app
      - ./vendor/bundle:/app/vendor/bundle
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      REDIS_URL: redis://redis
      DATABASE_URL: ${DATABASE_URL}
  sidekiq:
    build:
      context: .
      args:
        BUNDLE_DEPLOYMENT: 'false'
        BUNDLE_WITHOUT: ' ' # Intentional blank value
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis
  postgres:
    image: postgres:17.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: redis:alpine
    ports:
      - 6379
