inherit_from: ./.rubocop.yml

# Intentionally disabled as it doesn't fit with our code style.
RSpec/AnyInstance:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/ImplicitBlockExpectation:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false

# TODO: try to enable these
RSpec/ContextWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/RepeatedDescription:
  Enabled: false
RSpec/RepeatedExampleGroupDescription:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false

# TODO: try to reduce these
RSpec/ExampleLength:
  Max: 75
RSpec/MultipleExpectations:
  Max: 26
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Max: 12
