version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-eks: circleci/aws-eks@0.2.1
  kubernetes: circleci/kubernetes@0.7.0
  helm: circleci/helm@1.1.2
  newman: postman/newman@0.0.2

commands:
  checkout_and_decrypt:
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install git-crypt
      - run: echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
      - run: git-crypt unlock git-crypt.key

jobs:
  test:
    docker:
      - image: cimg/ruby:3.3.6
        environment:
          PAGER: cat
          DATABASE_URL: postgres://postgres@localhost/laa_court_data_adaptor_test
          RAILS_ENV: test
      - image: cimg/postgres:14.11
        environment:
          POSTGRES_DB: laa_court_data_adaptor_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install bundle
          command: |
            sudo gem install bundler -N

      - run:
          name: install dependencies
          command: |
            bundle check || bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:migrate

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: run rubocop
          command: bundle exec rubocop

  build-and-push-app:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - run: |
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
      - run:
          name: Set env vars
          command: |
            echo "export APP_BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z)"  >> "$BASH_ENV"
            source "$BASH_ENV"
      - aws-ecr/build_image:
          push_image: true
          tag: ${CIRCLE_SHA1}
          region: $ECR_REGION
          repo: $ECR_REPOSITORY
          account_id: "754256621582"
          extra_build_args: >-
            --build-arg BUILD_DATE=${APP_BUILD_DATE}
            --build-arg BUILD_TAG=${CIRCLE_SHA1}
            --build-arg COMMIT_ID=${CIRCLE_SHA1}
            --build-arg APP_BRANCH=${CIRCLE_BRANCH}

  install_on_dev_live:
    executor: aws-eks/python
    steps:
      - checkout_and_decrypt
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: 'v3.2.4'
      - run:
          name: Authenticate to LIVE cluster
          command: |
            echo -n ${CLUSTER_CERT_LIVE} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${CIRCLE_CI_TOKEN_DEV_LIVE}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=laa-court-data-adaptor-dev
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=laa-court-data-adaptor-dev get pods
      - helm/upgrade-helm-chart:
          namespace: laa-court-data-adaptor-dev
          update-repositories: false
          chart: ./helm_deploy/laa-court-data-adaptor
          release-name: laa-court-data-adaptor
          values: ./helm_deploy/laa-court-data-adaptor/public-values/dev.yaml
          values-to-override: image.tag=$CIRCLE_SHA1

  install_on_test_live:
    executor: aws-eks/python
    steps:
      - checkout_and_decrypt
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: 'v3.2.4'
      - run:
          name: Authenticate to LIVE cluster
          command: |
            echo -n ${CLUSTER_CERT_LIVE} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${CIRCLE_CI_TOKEN_TEST_LIVE}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=laa-court-data-adaptor-test
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=laa-court-data-adaptor-test get pods
      - helm/upgrade-helm-chart:
          namespace: laa-court-data-adaptor-test
          update-repositories: false
          chart: ./helm_deploy/laa-court-data-adaptor
          release-name: laa-court-data-adaptor
          values: ./helm_deploy/laa-court-data-adaptor/public-values/test.yaml
          values-to-override: image.tag=$CIRCLE_SHA1

  install_on_stage_live:
    executor: aws-eks/python
    steps:
      - checkout_and_decrypt
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: 'v3.2.4'
      - run:
          name: Authenticate to LIVE cluster
          command: |
            echo -n ${CLUSTER_CERT_LIVE} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${CIRCLE_CI_TOKEN_STAGE_LIVE}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=laa-court-data-adaptor-stage
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=laa-court-data-adaptor-stage get pods
      - helm/upgrade-helm-chart:
          namespace: laa-court-data-adaptor-stage
          update-repositories: false
          chart: ./helm_deploy/laa-court-data-adaptor
          release-name: laa-court-data-adaptor
          values: ./helm_deploy/laa-court-data-adaptor/public-values/stage.yaml
          values-to-override: image.tag=$CIRCLE_SHA1

  install_on_uat_live:
    executor: aws-eks/python
    steps:
      - checkout_and_decrypt
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: 'v3.2.4'
      - run:
          name: Authenticate to LIVE cluster
          command: |
            echo -n ${CLUSTER_CERT_LIVE} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${CIRCLE_CI_TOKEN_UAT_LIVE}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=laa-court-data-adaptor-uat
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=laa-court-data-adaptor-uat get pods
      - run:
          name: Deploy to UAT
          command: |
            .circleci/deploy.sh laa-court-data-adaptor-uat ./helm_deploy/laa-court-data-adaptor/public-values/uat.yaml $CIRCLE_SHA1

  install_on_prod_live:
    executor: aws-eks/python
    steps:
      - checkout_and_decrypt
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: 'v3.2.4'
      - run:
          name: Authenticate to LIVE cluster
          command: |
            echo -n ${CLUSTER_CERT_LIVE} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${CIRCLE_CI_TOKEN_PROD_LIVE}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=laa-court-data-adaptor-prod
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=laa-court-data-adaptor-prod get pods
      - run:
          name: Deploy to Production
          command: |
            .circleci/deploy.sh laa-court-data-adaptor-prod ./helm_deploy/laa-court-data-adaptor/live/prod/values-prod.yaml $CIRCLE_SHA1
  

  postman-test-dev:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./postman-collection/runner/tests.postman_collection.json
          environment: ./postman-collection/runner/env.postman_environment.json
          additional-options:  "--env-var client_id=$DEV_UID --env-var client_secret=$DEV_SECRET --env-var urn=PYDJQMBSED --env-var maat_id=3456786 --verbose"

workflows:
  version: 2
  test-build-deploy-main-to-live-cluster:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - build-and-push-app:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - install_on_dev_live:
          requires:
            - build-and-push-app
      - install_on_test_live:
          requires:
          - build-and-push-app
      - install_on_uat_live:
          requires:
          - build-and-push-app
      - install_on_stage_live:
          requires:
          - build-and-push-app
      - hold_install_on_prod:
          type: approval
          requires:
            - build-and-push-app
      - install_on_prod_live:
          requires:
          - hold_install_on_prod

  
  test-branch:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main

  build-deploy-branch-to-live-cluster:
    jobs:
      - build-and-push-app:
          filters:
            branches:
              ignore:
                - main
      - hold_install_on_dev:
          type: approval
          requires:
          - build-and-push-app
      - install_on_dev_live:
          requires:
          - hold_install_on_dev
      - hold_install_on_test:
          type: approval
          requires:
          - build-and-push-app
      - install_on_test_live:
          requires:
          - hold_install_on_test
      - hold_install_on_stage:
          type: approval
          requires:
          - build-and-push-app
      - install_on_stage_live:
          requires:
          - hold_install_on_stage
      - hold_install_on_uat:
          type: approval
          requires:
          - build-and-push-app
      - install_on_uat_live:
          requires:
          - hold_install_on_uat
      - postman-test-dev:
          name: postman-test-dev
