---
openapi: 3.0.1
info:
  title: Court Data Adaptor
  description: |-
    CDA exposes API endpoints to the LAA's View Court Data and
                          MAAT/MLRA applications and the HMCTS Common Platform in order to
                          exchange criminal court data between the two organisations.
  version: v2
paths:
  "/api/external/v2/hearing_results":
    post:
      summary: post hearing
      description: Post Common Platform hearing data to CDA
      tags:
      - External - available to Common Platform
      security:
      - oAuth: []
      parameters: []
      responses:
        '202':
          description: Accepted
        '422':
          description: Unprocessable Entity
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": hearing_resulted.json#/definitions/new_resource
        description: The minimal Hearing Resulted payload
  "/api/external/v2/prosecution_conclusions":
    post:
      summary: post prosecution conclusion
      description: Post Common Platform prosecution concluded data to CDA
      tags:
      - External - available to Common Platform
      security:
      - oAuth: []
      parameters: []
      responses:
        '202':
          description: Accepted
        '422':
          description: Unprocessable Entity
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": prosecution_concluded_request.json#/definitions/resource
        required: true
        description: The minimal prosecution concluded payload
  "/api/internal/v2/court_application_laa_references":
    post:
      summary: post laa_reference
      description: Post an LAA reference to CDA to link a MAAT case to a Common Platform
        application
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - "$ref": "#/components/parameters/transaction_id_header"
      responses:
        '201':
          description: created
        '422':
          description: Unprocessable entity
        '401':
          description: Unauthorized
        '424':
          description: Failed Dependency on Common Platform
      requestBody:
        content:
          application/json:
            schema:
              "$ref": laa_reference_post_request_body.json#
        description: The LAA issued reference to the application. CDA expects a numeric
          number, although HMCTS allows strings
  "/api/internal/v2/court_application_laa_references/{subject_id}":
    patch:
      summary: update laa_reference
      description: Update an LAA reference (mark as unlinked)
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - "$ref": "#/components/parameters/transaction_id_header"
      - name: subject_id
        in: path
        required: true
        type: uuid
        schema:
          "$ref": defendant.json#/properties/id
        description: The unique identifier of the defendant
      responses:
        '200':
          description: OK
        '422':
          description: Unprocessable Entity
        '404':
          description: Defendant not found
        '401':
          description: Unauthorized
        '424':
          description: Failed Dependency on Common Platform
      requestBody:
        content:
          application/json:
            schema:
              "$ref": laa_reference_patch_request_body.json#
        required: true
        description: The LAA issued reference to the application. CDA expects a numeric
          number, although HMCTS allows strings
  "/api/internal/v2/court_applications/{court_application_id}":
    get:
      summary: fetch a court application by ID
      description: find a court application where it exists within HMCTS
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - name: court_application_id
        in: path
        required: true
        type: uuid
        schema:
          "$ref": court_application.json#/properties/id
        description: The uuid of the court application
      - "$ref": "#/components/parameters/transaction_id_header"
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                "$ref": court_application_response.json#
        '503':
          description: Service unavailable
        '404':
          description: Resource not found
  "/api/internal/v2/prosecution_cases/{prosecution_case_reference}/defendants/{id}":
    get:
      summary: fetch a case defendant by ID
      description: find a defendant where it exists within Court Data Adaptor
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - name: prosecution_case_reference
        in: path
        required: true
        schema:
          "$ref": prosecution_case_identifier.json#/properties/case_urn
        description: The unique reference number (URN) of the case
      - name: id
        in: path
        required: true
        type: uuid
        schema:
          "$ref": defendant.json#/properties/id
        description: The uuid of the defendant
      - "$ref": "#/components/parameters/transaction_id_header"
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                "$ref": defendant_summary.json#
        '404':
          description: Not found
        '401':
          description: Unauthorized
  "/api/internal/v2/hearings/{hearing_id}/event_log/{date}":
    get:
      summary: fetch the hearing events log for a hearing
      description: fetch the hearing event logs for a hearing
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - name: hearing_id
        in: path
        required: true
        type: uuid
        description: The hearing UUID
        schema:
          "$ref": hearing.json#/properties/id
      - name: date
        in: path
        type: string
        required: true
        description: The date of the hearing
        schema:
          "$ref": definitions.json#/definitions/datePattern
      - "$ref": "#/components/parameters/transaction_id_header"
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                "$ref": hearing_event_log_response.json#
        '401':
          description: Unauthorized
        '404':
          description: not found
  "/api/internal/v2/hearing_results/{hearing_id}":
    get:
      summary: get hearing
      description: GET Common Platform hearing data
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - name: hearing_id
        in: path
        required: true
        type: uuid
        schema:
          "$ref": definitions.json#/definitions/uuid
        description: The uuid of the hearing
      - "$ref": "#/components/parameters/transaction_id_header"
      - name: sitting_day
        in: query
        required: false
        type: string
        format: datetime
        schema:
          "$ref": definitions.json#/definitions/datePattern
        description: The sitting day of the hearing
      - name: publish_to_queue
        in: query
        required: false
        description: Publish hearing results to MAAT API
        schema:
          type: boolean
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                "$ref": hearing_result.json#
        '401':
          description: Unauthorized
        '404':
          description: Not found
  "/api/internal/v2/laa_references":
    post:
      summary: post laa_reference
      description: Post an LAA reference to CDA to link a MAAT case to a Common Platform
        case
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - "$ref": "#/components/parameters/transaction_id_header"
      responses:
        '201':
          description: Created
        '424':
          description: Failed dependency
        '422':
          description: Unprocessable entity
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": laa_reference_post_request_body.json#
        description: The LAA issued reference to the application. CDA expects a numeric
          number, although HMCTS allows strings
  "/api/internal/v2/laa_references/{defendant_id}":
    patch:
      summary: update laa_reference
      description: Update an LAA reference (mark as unlinked)
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - "$ref": "#/components/parameters/transaction_id_header"
      - name: defendant_id
        in: path
        required: true
        type: uuid
        schema:
          "$ref": defendant.json#/properties/id
        description: The unique identifier of the defendant
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Defendant not found
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": laa_reference_patch_request_body.json#
        required: true
        description: The LAA issued reference to the application. CDA expects a numeric
          number, although HMCTS allows strings
  "/api/internal/v2/prosecution_cases":
    get:
      summary: search prosecution cases
      description: |-
        Search prosecution cases. Valid search combinations are: <br/><br/>
                            1) prosecution_case_reference <br/>
                            2) arrest_summons_number <br/>
                            3) national_insurance_number <br/>
                            4) name and date_of_birth <br/>
                            5) name and date_of_next_hearing
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - "$ref": "#/components/parameters/transaction_id_header"
      - name: filter[prosecution_case_reference]
        in: query
        required: false
        type: string
        schema:
          "$ref": prosecution_case_identifier.json#/properties/case_urn
        description: Searches prosecution cases by prosecution case reference
      - name: filter[arrest_summons_number]
        in: query
        required: false
        type: string
        schema:
          "$ref": defendant_summary.json#/properties/arrest_summons_number
        description: Searches prosecution cases by arrest summons number
      - name: filter[national_insurance_number]
        in: query
        required: false
        type: string
        schema:
          "$ref": person.json#/properties/nino
        description: Searches prosecution cases by national_insurance_number
      - name: filter[name]
        in: query
        required: false
        type: string
        schema:
          "$ref": person.json#/properties/last_name
        description: Searches prosecution cases by name
      - name: filter[date_of_birth]
        in: query
        required: false
        type: string
        schema:
          "$ref": person.json#/properties/date_of_birth
        description: Searches prosecution cases by date_of_birth
      - name: filter[name]
        in: query
        required: false
        type: string
        schema:
          "$ref": person.json#/properties/last_name
        description: Searches prosecution cases by name
      - name: filter[date_of_next_hearing]
        in: query
        required: false
        type: string
        schema:
          "$ref": definitions.json#/definitions/datePattern
        description: Searches prosecution cases by date_of_next_hearing
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                "$ref": search_prosecution_case_response.json#
        '424':
          description: Common Platform API Error
          content:
            application/vnd.api+json:
              schema:
                "$ref": search_prosecution_case_response.json#
        '503':
          description: Common Platform API Offline
        '401':
          description: Unauthorized
    post:
      summary: search prosecution cases
      description: |-
        Search prosecution cases. Valid search combinations are: <br/><br/>
                            1) prosecution_case_reference <br/>
                            2) arrest_summons_number <br/>
                            3) national_insurance_number <br/>
                            4) name and date_of_birth <br/>
                            5) name and date_of_next_hearing
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - "$ref": "#/components/parameters/transaction_id_header"
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                "$ref": search_prosecution_case_response.json#
        '424':
          description: Common Platform API Error
        '503':
          description: Common Platform API Offline
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              "$ref": prosecution_case_post_request_body.json#
        required: true
  "/api/internal/v2/representation_orders":
    post:
      summary: post representation_order
      description: Post a Representation Order to CDA to update the status on a MAAT
        case to a Common Platform case
      tags:
      - Internal - available to other LAA applications
      security:
      - oAuth: []
      parameters:
      - "$ref": "#/components/parameters/transaction_id_header"
      responses:
        '202':
          description: Accepted
        '422':
          description: Unprocessable entity
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": representation_order_request.json#
        required: true
        description: The Representation Order for an offence
components:
  securitySchemes:
    oAuth:
      in: header
      type: oauth2
      description: OAuth2 client credentials flow
      flows:
        clientCredentials:
          scopes: []
          tokenUrl: "/oauth/token"
  parameters:
    transaction_id_header:
      type: uuid
      name: X-Request-ID
      in: header
      required: false
      description: A unique identifier for an individual request that can be traced
        across multiple systems
      example: d7f509e8-309c-4262-a41d-ebbb44deab9e
