apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-court-data-adaptor.fullname" . }}-worker
  labels:
    {{- include "laa-court-data-adaptor.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.workerReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: laa-court-data-adaptor-worker
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: laa-court-data-adaptor-worker
    spec:
     {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
     {{- end }}
      serviceAccountName: {{ include "laa-court-data-adaptor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['bundle', 'exec', 'sidekiq']
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{ include "laa-court-data-adaptor.env-vars" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
