inherit_from:
  - ../.rubocop_rspec.yml
  - .rubocop_todo.yml

# make rspec formatting more flexible
Layout/MultilineMethodCallIndentation:
  Exclude:
    - '**/*_spec.rb'

# TODO: add parentheses for these and remove
Lint/AssignmentInCondition:
  Enabled: false

# `formula do` uses nested method definitions
Lint/NestedMethodDefinition:
  Exclude:
    - 'test/**/*'

# TODO: Try to bring down all metrics maximums.
Metrics/AbcSize:
  Max: 250
Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'test/**/*'
Metrics/BlockNesting:
  Max: 5
Metrics/ClassLength:
  Max: 800
  Exclude:
    - 'formula.rb'
    - 'formula_installer.rb'
Metrics/CyclomaticComplexity:
  Max: 80
Metrics/PerceivedComplexity:
  Max: 90
Metrics/MethodLength:
  Max: 260
Metrics/ModuleLength:
  Max: 600
  Exclude:
    - 'test/**/*'

Naming/PredicateName:
  # Can't rename these.
  AllowedMethods: is_32_bit?, is_64_bit?

Style/HashAsLastArrayItem:
  Exclude:
    - 'test/utils/spdx_spec.rb'
