---
http_interactions:
  - request:
      method: post
      uri: <MAAT_API_OAUTH_URL>/oauth2/token
      body:
        encoding: UTF-8
        string: grant_type=client_credentials
      headers:
        User-Agent:
          - Faraday v2.14.3
        Content-Type:
          - application/x-www-form-urlencoded
        Authorization:
          - "<AUTH>"
        Accept-Encoding:
          - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
        Accept:
          - "*/*"
    response:
      status:
        code: 200
        message: ""
      headers:
        Date:
          - Fri, 31 Jul 2026 15:22:22 GMT
        Content-Type:
          - application/json;charset=UTF-8
        Transfer-Encoding:
          - chunked
        Connection:
          - keep-alive
        X-Amz-Cognito-Request-Id:
          - 6b1d4aa5-d0b5-4a2a-b7e1-f12918b68e85
        Vary:
          - Access-Control-Request-Headers
          - Access-Control-Request-Method
          - Origin
        X-Content-Type-Options:
          - nosniff
        X-Xss-Protection:
          - "0"
        Cache-Control:
          - no-cache, no-store, max-age=0, must-revalidate
        Pragma:
          - no-cache
        Expires:
          - "0"
        Strict-Transport-Security:
          - max-age=31536000 ; includeSubDomains
        X-Frame-Options:
          - DENY
        Server:
          - Server
      body:
        encoding: UTF-8
        string: '{"access_token":"<access_token>","expires_in":3600,"token_type":"Bearer"}'
    recorded_at: Fri, 31 Jul 2026 15:22:22 GMT
  - request:
      method: post
      uri: <MAAT_API_API_URL>/api/internal/v1/assessment/rep-orders/search-maat-application
      body:
        encoding: UTF-8
        string: '{"firstName":"Tango","lastName":"JF-LAA-T"}'
      headers:
        User-Agent:
          - Faraday v2.14.3
        Authorization:
          - "<AUTH>"
        Content-Type:
          - application/json
        Accept-Encoding:
          - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
        Accept:
          - "*/*"
    response:
      status:
        code: 200
        message: ""
      headers:
        Date:
          - Fri, 31 Jul 2026 15:22:23 GMT
        Content-Type:
          - application/json
        Transfer-Encoding:
          - chunked
        Connection:
          - keep-alive
        Set-Cookie:
          - INGRESSCOOKIE=1785511343.432.31305.664596|55b9a069646b5e4eb9ec5bafd08dbaec;
            Max-Age=300; Path=/; Secure; HttpOnly
        X-Content-Type-Options:
          - nosniff
        X-Xss-Protection:
          - "0"
        Cache-Control:
          - no-cache, no-store, max-age=0, must-revalidate
        Pragma:
          - no-cache
        Expires:
          - "0"
        Strict-Transport-Security:
          - max-age=31536000; includeSubDomains
        X-Frame-Options:
          - DENY
      body:
        encoding: UTF-8
        string: '[{"maatId":6559879,"linkingDetail":null,"linked":false,"isLinked":false},{"maatId":6672961,"linkingDetail":{"libraId":"2600000358","caseId":1022118,"caseUrn":null,"cjsAreaCode":"01","cjsLocation":"B01OB"},"linked":true,"isLinked":true},{"maatId":6541616,"linkingDetail":{"libraId":"CP665948","caseId":1022017,"caseUrn":"CEXOFJTQ2F","cjsAreaCode":"01","cjsLocation":"B01BH"},"linked":true,"isLinked":true}]'
    recorded_at: Fri, 31 Jul 2026 15:22:23 GMT
recorded_with: VCR 6.4.0
