name: Brakeman

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
    - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1
    - run: gem install brakeman --version 6
    - run: brakeman
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
