name: Brakeman

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5
    - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1
    - run: gem install brakeman --version 6
    - run: brakeman
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
